"""
Module ai.py
============

This module contains all of the functions related to the computer's AI and the NegaMax algorithm
"""
from typing import Set

from src.constants import GameState, MAX_SCORE

__all__ = ['has_won', 'evaluate', 'alpha_beta']
__version__ = '0.1'
__author__ = 'Eric G.D'


# TODO: Implement this module's fumctions


def has_won(board: GameState) -> bool:
    """
    :param board:   The game board
    :return: True if there is a row of 4 pieces, False otherwise
    """
    return abs(evaluate(board)) == MAX_SCORE


def evaluate(board: GameState, color: str = 'red') -> int:
    """
    :param board: A simplified game board generated by Board.convert()
    :param color: The current player's token color
    :return: The heuristic value of the board relative to a draw (0)
    """
    return 0  # Placeholder


def alpha_beta(board: GameState, color: str, move_set: Set[int], alpha: float, beta: float, depth: int):
    """
    :param board:
    :param color:
    :param move_set:
    :param alpha:
    :param beta:
    :param depth:
    :return:
    """
    # TODO: Document this function
    pass
